#!/bin/bash 
# This is a test bash script


echo Dowloading Spigot Build Tools.
wget https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar -O BuildTools.jar
echo Building spigot to be used a a library.
git config --global --unset core.autocrlf
java -jar BuildTools.jar --rev 1.16.4 --output-dir ./libs
